### PR TITLE
Added Naming Convention

### PR DESCRIPTION
**Pull request by rohit-kumar-j**
Tested with both `cmake-kits.json` and `CMakeKits.json`

### CODE REVIEW

**Comment by Civitasv** [comment]
Why is it useful?

**Comment by Civitasv** [comment]
VsCode's cmake-tools only supports `cmake-kits.json`. If our plugin also supports `CMakeKits.json`, then users can't use both neovim and vscode. I think it is not suitable. What do you think about it?

**Comment by rohit-kumar-j** [comment]
Oh, I didn't know about that!😅. I thought that VS Code supported `CMakeKits.json` since the convetions were caplitalized letters in `CMakeLists.txt` and `CMakeUserPresets.json`,etc and the readme had it caplitalized.

> Attention: If CMake[User]Presets.json is provided, then CMakeKits.json or CMakeVariants.[json|yaml] won't have any effect.

However, wouldn't it be alright since this supports both?:
```lua
 if (f == "cmake-kits.json" or f == "CMakeKits.json")  
```

**Comment by Civitasv** [comment]
You've convinced me.

**Pull request merged**
