### PR TITLE
feat: add option to not resize the terminal (#247)

### PR DESCRIPTION
**Pull request by lceWolf**
I'm not sure if the option name is fitting. I am open to suggestions.

Open question: Should the `keep_terminal_size` option be `true` per default?

### CODE REVIEW

**Comment by lceWolf** [comment]
renamed the option - I think this fits way better.

Still, should the default behaviour be changed to not automatically resize the terminal, or should it be kept opt-in?

**Comment by Civitasv** [comment]
> should the default behaviour be changed to not automatically resize the terminal

I don't think so. It should be kept opt-in.

**Comment by Civitasv** [comment]
Thanks for your contributing!

**Comment by lceWolf** [comment]
I think issue #247 can be closed now @Civitasv

**Pull request merged**
