### PR TITLE
feat: add option to run all tests to run_test()

### PR DESCRIPTION
**Pull request by khris190**
just added a option to use run_test({runAll = true}) to skip selecting tests and run all of them

### CODE REVIEW

**Comment by Civitasv** [comment]
Thanks for your contribution! Please change `runAll` to `run_all`. Add add description to [all_commands](https://github.com/Civitasv/cmake-tools.nvim/blob/master/docs/all_commands.md).

**Comment by khris190** [comment]
> Thanks for your contribution! Please change `runAll` to `run_all`. Add add description to [all_commands](https://github.com/Civitasv/cmake-tools.nvim/blob/master/docs/all_commands.md).

I just realised how opts work in user_command, what would be the correct way to implement it, I'm thinking about changing the way I did this, so I would add an option to vim.ui.select all_tests at the top of the list called "run all",
but i dont know how to deal with the user_command because what i really wanted was to add a lua script way of running all the tests for a keybind and i dont really know how to deal with the user_command args so that those 2 can coexist in a clean way.

**Comment by khris190** [comment]
i changed the way i did this so it just shows new option to run all tests
screen

**Comment by Civitasv** [comment]
Yeah, this is better.

**Pull request merged**
