### PR TITLE
feat: support default build (empty) preset;

### PR DESCRIPTION
**Pull request by LinHeLurking**

### CODE REVIEW

**Comment by LinHeLurking** [comment]
I'm sorry that the auto-formatter changes some code styles and trailing commas 😢. Actually I just changed these lines (https://github.com/Civitasv/cmake-tools.nvim/pull/16/files#diff-ec6b3a3b14fd0188bb323b958aa56e07af863c7256cd609c70539ef0df9ffff1R177-R181)

**Comment by Civitasv** [comment]
Yeah, can you only change these lines? You can use `git rebase -i` to merge your local commit.

**Comment by LinHeLurking** [comment]
I've reverted and committed again.

**Comment by Civitasv** [comment]
Thanks.

**Pull request merged**
