### PR TITLE
Configure target specific environment variables

### PR DESCRIPTION
**Pull request by hfn92**
As discussed here: https://github.com/Civitasv/cmake-tools.nvim/issues/90

Works for me but probably requires some additional testing. Especially for windows users.

### CODE REVIEW

**Comment by Civitasv** [comment]
I will test it soon.

**Comment by hfn92** [comment]
> I will test it soon.

Thanks :) Sorry for the PR spam :pray: 

I was wondering. Before you merge it, should I adapt it for what was discussed here? https://github.com/Civitasv/cmake-tools.nvim/issues/100 Right know the config window is only intended for env vars?

**Comment by Civitasv** [comment]
> Thanks :) Sorry for the PR spam

Don’t be sorry, thanks for your contribution to make it better. 😄 

> Before you merge it, should I adapt it for what was discussed here?

I think it’s a good idea to implement now, then I can review all of them.

**Comment by hfn92** [comment]
> I think it’s a good idea to implement now, then I can review all of them.

Ok will do. This is not a major change.  Just some renaming. So you are still free to review the current state :)

**Comment by Civitasv** [comment]
Okay 👍

**Review by Civitasv — APPROVED** [review]

**Comment by hfn92** [comment]
I just noticed that its probably better to persist settings as table instead of a string ...

so instead of
```lua
base_settings = "return {\n  env = {\n    VERBOSE=1\n  }\n}\n",
```
it should be like this (in session config)
```
base_settings = {  env =  { VERBOSE=1 } },
```

What do you think? I could still change that

**Comment by Civitasv** [comment]
I agree with you, table is more primitive in lua.

**Comment by hfn92** [comment]
> I agree with you, table is more primitive in lua.

A disadvantage is that comments won't be saved. A user might want to uncomment something for later use .

**Comment by Civitasv** [comment]
That's a case. Suddenly I think the string format maybe better lol. What do you think?

**Comment by hfn92** [comment]
Its tricky huh :D 
A table would have the advantage that it can be easily extended with missing settings if we add new ones. 
We could use strings in memory but persist tables. So comments would exist for the current instance but not be saved.
I'll think about it a bit

**Comment by Civitasv** [comment]
> We could use strings in memory but persist tables. So comments would exist for the current instance but not be saved.

yeah, it’s better.

**Comment by hfn92** [comment]
I decided against using both. Its easier to manage this way and more consistent between usage and allows for easier detection if something is wrong. And we can extend the table with defaults if something is missing at runtime.  But switching to using strings is always possible later.

**Comment by Civitasv** [comment]
Yes, I agree with you.

**Comment by Civitasv** [comment]
Please fix the conflicts then we can merge to master.

**Comment by hfn92** [comment]
> Please fix the conflicts then we can merge to master.

I tried twice locally. Not sure why it didn't work :/ Worked on gh directly though

**Comment by Civitasv** [comment]
And you should fix the format

**Pull request merged**
