### PR TITLE
Updated readme with defaults

### PR DESCRIPTION
**Pull request by rohit-kumar-j**

### CODE REVIEW

**Comment by rohit-kumar-j** [comment]
I think the commit history needs to be short on this one. How do I do this?

**Comment by rohit-kumar-j** [comment]
Is it necessary to shorten this?

**Comment by Civitasv** [comment]
I’ve squash your commits into one commit and merge into master. So you may need to force pull(I don’t know if it exists) to your master branch. Or you can delete your branch and make new branch based on master branch of this repo.

**Comment by rohit-kumar-j** [comment]
I have pulled, it says 24 commits ahead. Instead of up-to-date. Should I discrad?

**Comment by rohit-kumar-j** [comment]
Let me close this PR and discard commits.

**Comment by Civitasv** [comment]
Maybe use `git pull --force <origin> master`?

**Comment by rohit-kumar-j** [comment]
Does not seem to do it.

**Comment by rohit-kumar-j** [comment]
Seeing [lazgit](https://www.youtube.com/watch?v=CPLdltN7wgE&ab_channel=JesseDuffield) if it has something that I can use. :D

**Comment by Civitasv** [comment]
Or you can checkout a new branch from origin(Civitasv/cmake-tools.nvim) then making changes.

**Comment by rohit-kumar-j** [comment]
Permission deined lol. I will delete branch and re-create it.

**Pull request closed without merging**
