### PR TITLE
Replace video with gif

### PR DESCRIPTION
**Pull request by MartinDelille**
Since the video preview doesn't work, I created a gif from it.

### CODE REVIEW

**Comment by MartinDelille** [comment]
You can see the result here: https://github.com/Civitasv/cmake-tools.nvim/blob/f81a84602fe79f5d90a1541c52d7102425f04baf/README.md

**Comment by Civitasv** [comment]
Move demo.gif to a separate directory.

**Comment by Civitasv** [comment]
And I wonder why it doesn't work for you. It works for me.

**Comment by thetic** [comment]
it doesn't work for me either.

**Comment by Civitasv** [comment]
> it doesn't work for me either.

Interesting 🧐

**Comment by squattingmonk** [comment]
For me Firefox doesn't display because it says the file is corrupt. It displays in Chromium, however.

**Comment by thetic** [comment]
I'm also using Firefox.

**Comment by MartinDelille** [comment]
Does the video on the current [README.md](https://github.com/Civitasv/cmake-tools.nvim/blob/master/README.md) works for anyone ?

**Pull request merged**
