### PR TITLE
feat(tmux): Execute and Run with tmux

### PR DESCRIPTION
**Pull request by amirt01**
I use this plugin heavily in my workflow, but I want to use tmux to execute and run my projects. So far, I've gotten some basic functionality working, but there are many bugs that need fixing and features I'd like to add. I am using vimux as the integration layer between neovim and tmux. I created this draft pr to gauge interest in this functionality and get feedback from the maintainers.

### CODE REVIEW

**Comment by Civitasv** [comment]
I think this feature is quite useful!

**Comment by liketoeatcheese** [comment]
This would be so good

**Comment by amirt01** [comment]
Awesome! All you need to do to use vimux is specify vimux as your cmake_executor and/or cmake_runner like so:
```
opts = {
  cmake_executor = { name = "vimux", opts = {} },
  cmake_runner = { name = "vimux", opts = {} },
},
```
Here is the current feature status:

**Working features:**
- `CMakeBuild`
- `CMakeClean`
- `CMakeCloseExecuter`
- `CMakeCloseRunner`
- `CMakeQuickBuild`
- `CMakeQuickRun`
- `CMakeRun`
- `CMakeRunTest`
- `CMakeStopExecutor`
- `CMakeStopRunner`

**Features in development:**
- `CMakeBuildCurrentFile`
- `CMakeOpenExecutor`
- `CMakeOpenRunner`

**Known broken features:**
- `CMakeDebug`
- `CMakeDebugCurrentFile`
- `CMakeQuickDebug`

I'll keep y'all posted on my future work!

**Comment by liketoeatcheese** [comment]
Is this correct?
```lua
return {
	"amirt01/cmake-tools.nvim",
	config = function()
		local osys = require("cmake-tools.osys")
		require("cmake-tools").setup({
			cmake_command = "cmake", -- this is used to specify cmake command path
			ctest_command = "ctest", -- this is used to specify ctest command path
			cmake_use_preset = true,
			cmake_regenerate_on_save = true, -- auto generate when save CMakeLists.txt
			cmake_generate_options = { "-DCMAKE_EXPORT_COMPILE_COMMANDS=1" }, -- this will be passed when invoke `CMakeGenerate`
			cmake_build_options = {}, -- this will be passed when invoke `CMakeBuild`
			-- support macro expansion:
			--       ${kit}
			--       ${kitGenerator}
			--       ${variant:xx}
			cmake_build_directory = function()
				if osys.iswin32 then
					return "out\\${variant:buildType}"
				end
				return "out/${variant:buildType}"
			end, -- this is used to specify generate directory for cmake, allows macro expansion, can be a string or a function returning the string, relative to cwd.
			cmake_soft_link_compile_commands = true, -- this will automatically make a soft link from compile commands file to project root dir
			cmake_compile_commands_from_lsp = false, -- this will automatically set compile commands file location using lsp, to use it, please set `cmake_soft_link_compile_commands` to false
			cmake_kits_path = nil, -- this is used to specify global cmake kits path, see CMakeKits for detailed usage
			cmake_variants_message = {
				short = { show = true }, -- whether to show short message
				long = { show = true, max_length = 40 }, -- whether to show long message
			},
			cmake_dap_configuration = { -- debug settings for cmake
				name = "cpp",
				type = "codelldb",
				request = "launch",
				stopOnEntry = false,
				runInTerminal = true,
				console = "integratedTerminal",
			},
			cmake_executor = { -- executor to use
				name = "vimux", -- name of the executor
                                opt = {},
			},
			cmake_runner = { -- runner to use
				name = "vimux", -- name of the runner
                                opt = {},
			},
			cmake_notifications = {
				runner = { enabled = true },
				executor = { enabled = true },
				spinner = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" }, -- icons used for progress display
				refresh_rate_ms = 100, -- how often to iterate icons
			},
			--[[ cmake_virtual_text_support = true, -- Show the target related to current file using virtual text (at right corner) ]]
		})
	end,
}
```

I'm getting the error below when doing `CMakeRun`:
```text
Error executing Lua callback: ...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/vimux.lua:14: attempt to call field 'prepare_cmd_for_run' (a nil value)
stack traceback:
        ...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/vimux.lua:14: in function 'run'
        ...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:240: in function <...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:227>
```

Confirming that vimux from this pull request is in the version of cmake-tool I'm using:
image

**Comment by amirt01** [comment]
Thank you, @liketoeatcheese, for the catch. The terminal executor/runner was modified since I last merged. I've reintroduced the removed functions to make my vimux implementation work. Please let me know if you find any further issues.

For reference, here is how I use my fork with the Lazy.nvim plugin:

```
{
    "amirt01/cmake-tools.nvim",
    dependencies = { "preservim/vimux" },
    ft = { "cpp" },
    opts = {
      cmake_executor = { name = "vimux", opts = {} },
      cmake_runner = { name = "vimux", opts = {} },
    },
}
```

**Comment by liketoeatcheese** [comment]
Worked like a charm. Thank you legend!

**Comment by Civitasv** [comment]
Fantastic!

**Pull request merged**
