### PR TITLE
Fix buffer handling in windows 10, and added Autocmd 

### PR DESCRIPTION
**Pull request by rohit-kumar-j**
Fix buffer handling in windows 10, and added Autocmd for scrolling buffer output after process completion.

- [x] Tested on Windows 10
- [x] Tested on Linux
- [ ] Tested on MacOS

### CODE REVIEW

**Comment by rohit-kumar-j** [comment]
set_bufname throws error, disabling it.

**Comment by Civitasv** [comment]
Okay

**Comment by Civitasv** [comment]
Is it ready to merge?

**Comment by rohit-kumar-j** [comment]
Yes

**Comment by rohit-kumar-j** [comment]
The current behaviour is to not set any name and delete buffer. Will send a fix soon. FOr now it works as expected.

**Pull request merged**
